In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2,3,4])
x

array([0, 1, 2, 3, 4])

In [3]:
w = np.array([[0,1,2,3],[4,5,6,7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
np.square(y)

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [6]:
np.mean(y)

3.5

In [7]:
import pandas as pd

In [8]:
w = np.arange(8).reshape(2, 4)
df = pd.DataFrame(w)

In [9]:
df.colums = ['first', 'this', 'that', 'last']
df.index = ['row_1', 'row_2']

In [10]:
df = pd.DataFrame(w, columns=['first', 'this', 'that', 'last'], index=['row_1', 'row_2'])

In [11]:
names = ['George',
                       'John',
                       'Thomas',
                       'James',
                       'Andrew',
                       'Martin',
                       'William',
                       'Zachary',
                       'Millard',
                       'Franklin']

In [12]:
purchases = pd.DataFrame(index = names)
purchases

Empty DataFrame
Columns: []
Index: [George, John, Thomas, James, Andrew, Martin, William, Zachary, Millard, Franklin]

In [13]:
purchases["country"] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases["ad_views"] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases["items_purchased"] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [14]:
purchases["country"]

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [15]:
purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [16]:
purchases['items_purch_per_ad'] = purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [17]:
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [18]:
purchases.ix[:,'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [19]:
purchases.ix['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [20]:
purchases.ix['George', 'country']

'US'

In [21]:
purchases.ix[1:3, 1]

John      42
Thomas    32
Name: ad_views, dtype: int64

In [22]:
purchases[purchases['items_purchased']>1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [23]:
# this is the same as above
purchases.ix[lambda x: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [24]:
purchases[purchases['items_purchased']>1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [25]:
purchases.groupby('country').mean()

ad_views  items_purchased  items_purch_per_ad
country                                               
CAN         38.25             0.25            0.005952
US          35.50             5.00            0.217767

In [26]:
## You can also use and "&" or "|" not "~"
# http://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing
purchases[(purchases['items_purchased']>1) & ~(purchases['items_purchased']==2)]

country  ad_views  items_purchased  items_purch_per_ad
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [64]:
# Mentor session
df = pd.DataFrame([2,3,4,12,3,4,1])

In [68]:
df['names'] = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [74]:
new_df = df.set_index(df['names'])

In [75]:
new_df

0 names
names          
a       2     a
b       3     b
c       4     c
d      12     d
e       3     e
f       4     f
g       1     g

In [84]:
purchases.ix[1:4,0]

John      CAN
Thomas    CAN
James      US
Name: country, dtype: object

In [95]:
purchases.ix[lambda x: x['items_purchased'] > 3, :]

country  ad_views  items_purchased  items_purch_per_ad
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Franklin      US        77                5            0.064935

In [96]:
# This is the same as above, but faster
purchases[purchases['items_purchased'] > 3]

country  ad_views  items_purchased  items_purch_per_ad
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Franklin      US        77                5            0.064935

In [98]:
purchases.groupby('country').mean()

ad_views  items_purchased  items_purch_per_ad
country                                               
CAN         38.25             0.25            0.005952
US          35.50             5.00            0.217767